# We are going to cover:
* Introduction to tensor
* Getting info from tensors
* Manipulating tensors
* Tensors & numpy
* Using @tf.function (a way to speed up your regular python functions)
* Using GPUs with Tensorflow (or TPUs)
* Exercises to try

# Introduction to Tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
# Create tensors using tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check number of dimensions of a tensor
scaler.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of vector
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check the dimension of matrix
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Let's create another tensor
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
# Check the dimension of another tensor
tensor.ndim

3

# Creating tensors with `tf.variable`

In [ ]:
# Create the same tensor as above
changeable_vector = tf.Variable([10, 7])
unchangeable_vector = tf.constant([10, 7])

changeable_vector, unchangeable_vector

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Assign element in changeable_vector using .assign
changeable_vector[0].assign(7)
changeable_vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# Creating random tensors
### Random tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
# Create 2 random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle the order of elements in tensor

In [ ]:
# Shuffle a tensor
not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])

# Shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(32) # global level random seed
tf.random.shuffle(not_shuffled, seed=32) # operation level random seed


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

# Other ways to make tensors

In [ ]:
# Create a tensor with all ones
tf.ones([4, 6])

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeroes
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors
The main difference between NumPy arrays and Tensorflow tensors is that tensors can be run on GPU

In [ ]:
# Turning numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
# 2 * 3 * 4 = 24
B = tf.constant(numpy_A, shape=(2, 3, 4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# Getting information from tensors
### When dealing with tensors, you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("Data type of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Data type of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing Tensors
Tensors can be indexed just like python lists

In [ ]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [ ]:
# Get the first 2 elements of each dimensions
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the second last one
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[3, 4], [10, 7]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
# Get the last element of each or our rank_2_tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 7], dtype=int32)>

### Add in an extra dimension to our rank_2_tensor

In [ ]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 4]],

       [[10],
        [ 7]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 4]],

       [[10],
        [ 7]]], dtype=int32)>

In [ ]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[ 3,  4],
        [10,  7]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7]], dtype=int32)>

# Manipulating Tensors (tensor operations)

**Basic Operations**

`+`, `-`, `*`, `/`

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Multiplication
tensor = tensor * 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [ ]:
# Substraction
tensor = tensor - 100
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# We can use built in tensorflow function too
tensor = tf.multiply(tensor, 10)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000,  700],
       [ 300,  400]], dtype=int32)>

# Matrix multiplication
### In machine learning, matrix multiplication is one of the most common tensor operations.

In [ ]:
# Matrix multiplication in tensorflow
tensor = tf.constant([[10, 7], [3, 4]])
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Create a tensor (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create a tensor (3, 2)
Y = X

# Let's change the shape of y to be able to matmul
Y = tf.reshape(Y, shape=(2, 3))

X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

# Dot product
## Matrix multiplication is also referred to as the dot product
### You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [ ]:
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Print values of Y, reshaped Y and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


### Changing the datatype of a tensor

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B.dtype

tf.float16

In [ ]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C.dtype

tf.float32

## Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
A = tf.constant([-10, -5])

tf.abs(A)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  5], dtype=int32)>

### Types of aggregation function
* min
* max
* mean
* sum
* Variance
* Standard deviation

In [ ]:
# Define a tensor
tensor = tf.constant([10, 4, 3, 9, 5])

# Get the min value
print("Min value:", tf.reduce_min(tensor).numpy())

# Get the max value
print("Max value:", tf.reduce_max(tensor).numpy())

# Get the mean of all values in the tensor
print("Mean:", tf.reduce_mean(tensor).numpy())

# Get the sum of all the values in the tensor
print("Sum:", tf.reduce_sum(tensor).numpy())

# Get the variance
x = tf.cast(tensor, dtype=tf.float32)
print("Variance:", tf.math.reduce_variance(x).numpy())

# Get the standard deviation
print("Standard deviation:", tf.math.reduce_std(x).numpy())

Min value: 3
Max value: 10
Mean: 6
Sum: 31
Variance: 7.7599998
Standard deviation: 2.7856777


### Finding the positional minimum and maximum (argmin & argmax)

In [ ]:
# Create a new tensor
tf.random.set_seed(32)
tensor = tf.random.uniform(shape=[50], seed=32)
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.54560506, 0.35699224, 0.5322254 , 0.1631242 , 0.27250314,
       0.37481475, 0.3444605 , 0.5473776 , 0.54002583, 0.14926863,
       0.26532435, 0.92027533, 0.09836185, 0.9124472 , 0.33488584,
       0.80210125, 0.20069838, 0.893291  , 0.22261024, 0.3221054 ,
       0.22319019, 0.86107814, 0.16530848, 0.55119693, 0.99174476,
       0.08621192, 0.47624004, 0.9976859 , 0.87391174, 0.44218373,
       0.44642878, 0.03260744, 0.8476907 , 0.17135096, 0.03069556,
       0.31885362, 0.7664542 , 0.0132426 , 0.85578096, 0.61706245,
       0.50358737, 0.6157217 , 0.83949447, 0.9241518 , 0.5027126 ,
       0.2574035 , 0.36856472, 0.49492586, 0.2645793 , 0.28591764],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=27>

In [ ]:
# Index on our largest element
tensor[tf.argmax(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9976859>

In [ ]:
# Find the max value of tensor
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9976859>

In [ ]:
# Check for equality
tensor[tf.argmax(tensor)] == tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the positional minimum
tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [ ]:
# Index of the minimum element
tensor[tf.argmin(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.013242602>

In [ ]:
# Find the min value of tensor
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.013242602>

In [ ]:
# Check for equality
tensor[tf.argmin(tensor)] == tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
from random import seed
# Create a tensor
tf.random.set_seed(32)
A = tf.constant(tf.random.uniform(shape=[50]), shape=[1, 1, 1, 1, 50])
A

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.54520595, 0.13372338, 0.45232666, 0.15582252, 0.9621073 ,
           0.8151462 , 0.4068215 , 0.9565903 , 0.5532354 , 0.44936454,
           0.01469815, 0.86204493, 0.12014258, 0.91072273, 0.00848019,
           0.62772846, 0.8167286 , 0.98235905, 0.06410611, 0.17873585,
           0.07358396, 0.95524645, 0.5906956 , 0.3774085 , 0.9427308 ,
           0.32449841, 0.05033565, 0.6481848 , 0.97997856, 0.7848562 ,
           0.8223983 , 0.25406194, 0.21289039, 0.18566561, 0.18804717,
           0.5875702 , 0.45183384, 0.5508704 , 0.18366766, 0.55480397,
           0.72248566, 0.66862214, 0.46865964, 0.50943816, 0.61882794,
           0.5858562 , 0.7246859 , 0.88589907, 0.7049539 , 0.00409675]]]]],
      dtype=float32)>

In [ ]:
A.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
A_squeezed = tf.squeeze(A)
A_squeezed.shape

TensorShape([50])

### One-Hot Encoding

In [ ]:
# Create a list
some_list = [0, 1, 2, 3] # red, green, blue, yellow

# one hot enocde the list
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one-hot encoding
tf.one_hot(some_list, depth=4, on_value="Yes", off_value="No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

### Squaring , log and square root

In [ ]:
# Create a new tensor
tensor = tf.range(1, 10)
tensor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square
tf.square(tensor)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Square root (method requires non-int type)
tf.sqrt(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# log (method requires non-int type)
tf.math.log(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensorflow and numpy
Tensorflow interacts beautifully with numpy arrays

In [ ]:
# Create a tensor directly from numpy array
tensor = tf.constant(np.array([1, 2, 3]))
tensor

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [ ]:
# Convert our tensor back to numpy array
np.array(tensor), type(np.array(tensor))

(array([1, 2, 3]), numpy.ndarray)

In [ ]:
# another way
tensor.numpy(), type(tensor.numpy())

(array([1, 2, 3]), numpy.ndarray)

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]